### ISSUE TITLE
 Issue: python STSS.py --dir downloaded_genomes/

### ISSUE THREAD

**Issue by javobio8** [kew222/Self-Targeting-Spacer-Searcher#3]
Dear Kyle,

Thanks for sharing this great software. It runs well with the format --search. 
However, when I execute: 
**input:** python STSS.py --dir downloaded_genomes/
**Folder:** two files in fasta format.
**output:**  "You must provide an operation to perform" and the menu options.

I tried also to combine with other commands from the menu options but none of them seems to work. 

Thank you.

Best regards,
Javier Munoz

**Comment by kew222** [comment]
Hi Javier,

Sorry for issue, it was a small oversight in the options. I've updated the code to fix the issue and it should run properly now. Please note that the functionalities are somewhat limited for genomes that cannot be found on NCBI. 

These changes are in the v1.1.1 release.
